#!/bin/bash
#mos-c64-clang main.c -o program.prg
#mos-c128-clang -D__C128__ render.c vsync.c main.c -o program128.prg
#cl65 -t c64 main.c -o program.prg
#cl65 -t c128 -Os render.c vsync.c main.c -o program128.prg
oscar64 -Os -o=program.prg main.c
